# -*- mode: ruby -*-
# vi: set ft=ruby :
# Maintainer: Rajesh Raheja
# November 2015

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"


  $script = <<-SCRIPT
    sudo apt-get update
    sudo apt-get install -y unzip curl
    sudo apt-get install haproxy
    
    cd /tmp/
    wget https://releases.hashicorp.com/consul-template/0.12.2/consul-template_0.12.2_linux_amd64.zip

    echo Installing Consul-Template...
    unzip consul-template_0.12.2_linux_amd64.zip

    echo Fetching Consul...
    cd /tmp/
    wget https://releases.hashicorp.com/consul/0.6.1/consul_0.6.1_linux_amd64.zip - O consul.zip
    echo Installing Consul...
    unzip consul_0.6.1_linux_amd64.zip
    sudo chmod +x consul
    sudo mv consul /usr/bin/consul
    sudo mkdir /etc/consul.d
    sudo chmod a+w /etc/consul.d
    
    echo Fetching Consul-Template...
    cd /tmp/
    wget https://releases.hashicorp.com/consul-template/0.12.2/consul-template_0.12.2_linux_amd64.zip

    echo Installing Consul-Template...
    unzip consul-template_0.12.2_linux_amd64.zip
   
  SCRIPT

  config.vm.provision "shell", inline: $script

  config.vm.define "n1" do |n1|
      n1.vm.hostname = "n1"
      n1.vm.network "private_network", ip: "172.20.20.10"
end
end