# -*- mode: ruby -*-
# vi: set ft=ruby :

unless Vagrant.has_plugin?("vagrant-docker-compose")
  system("vagrant plugin install vagrant-docker-compose")
  puts "Dependencies installed, please try the command again."
  exit
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  

  config.vm.provision :shell, inline: "sudo sudo rm -rf /var/lib/apt/lists/* &&
 apt-get update"
  config.vm.provision :docker
  config.vm.provision :docker_compose, yml: ["/vagrant/containers.yml"], rebuild: true, project_name: "myproject", run: "always"

  config.vm.define "n1" do |n1|
      n1.vm.hostname = "n1"
      n1.vm.network "private_network", ip: "172.20.20.10"
      end
end